name: Automated Hotfix Process

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
        description: "The tag name of the hotfix release"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs: 
  cherry-pick-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Cherry-pick hotfix to main
        run: |
          # Fetch all branches and tags
          git fetch origin --tags
          
          # Get hotfix tag and main branch
          git checkout ${{ inputs.tag_name }}
          
          # Get last commit from the hotfix release
          COMMIT_HASH=$(git rev-parse HEAD)
          
          # Checkout main and cherry-pick
          git checkout main
          git pull origin main
          
          # Try cherry-pick with --no-changelog flag to prevent duplicate changelog entries
          git cherry-pick -x $COMMIT_HASH -m "fix: cherry-pick hotfix from ${{ inputs.tag_name }} --no-changelog"
          
          # Push changes to main
          git push origin main 