on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: Automated Release and Deployment

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
         
  # This job will trigger when a new release is created
  deploy-after-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/prod-deploy.yaml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
