on:
  push:
    branches:
      - main
      - 'hotfix/*'

permissions:
  contents: write
  pull-requests: write
  issues: write

name: Automated Release and Deployment

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: ${{ github.ref_name }}  
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
         
  # This job will trigger when a new release is created from any branch
  deploy-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/prod-deploy.yaml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}

  # This job will cherry-pick hotfix changes to main when a hotfix is released
  cherry-pick-to-main:
    needs: [release-please, deploy-release]
    if: ${{ needs.release-please.outputs.release_created && startsWith(github.ref, 'refs/heads/hotfix-') }}
    uses: ./.github/workflows/hotfix.yaml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
